name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  TF_WORKING_DIR: terraform/static-web-app

jobs:
  fmt:
    name: Terraform fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt check
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt -check -recursive

  validate:
    name: Terraform validate
    runs-on: ubuntu-latest
    needs: fmt
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -input=false

      - name: Terraform validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

  security_scan:
    name: Security Scan (tfsec)
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install tfsec
        run: |
          wget https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64
          chmod +x tfsec-linux-amd64
          sudo mv tfsec-linux-amd64 /usr/local/bin/tfsec

      - name: Run tfsec security scan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: tfsec .

  plan:
    name: Terraform plan
    runs-on: ubuntu-latest
    needs: security_scan
    outputs:
      plan-file: ${{ steps.plan.outputs.planfile }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -input=false

      - name: Terraform plan
        id: plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform plan -input=false -out=tfplan.binary
          terraform show -json tfplan.binary > tfplan.json
        
      - name: Upload plan artifact
        uses: actions/upload-artifact@v3
        with:
          name: tfplan
          path: |
            ${{ env.TF_WORKING_DIR }}/tfplan.binary
            ${{ env.TF_WORKING_DIR }}/tfplan.json

      - name: Comment PR with plan
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: ${{ env.TF_WORKING_DIR }}/tfplan.json

  apply:
    name: Terraform apply
    runs-on: ubuntu-latest
    needs: plan
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Download plan artifact
        uses: actions/download-artifact@v3
        with:
          name: tfplan
          path: ${{ env.TF_WORKING_DIR }}

      - name: Terraform apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        run: terraform apply -input=false -auto-approve tfplan.binary
